name: Rawr
pygments: true

navigation:
  - text: Home
    url: /index.html
    group: home
  - text: Docs
    url: http://rawr.readthedocs.org
    group: docs
  - text: Getting Started
    url: /community/index.html
    group: community
  - text: Download
    url: /download/index.html
    group: download
