name: Capivaras
pygments: true

favorite:
  - language: Haskell
    descr: A pure functional programming language.
  - language: Livescript
    descr: An hybrid functional language that compiles to Javascript.
  - language: F#
    descr: The better language of CLR that I ever knew!
  - language: Erlang
    descr: Built to build concurrent webservers.

proglang:
  - language: "Ada"
    descr: "We have the real time and the Ada time."
  - language: "AdvPL"
    descr: "A proprietary language built by Totvs, a Clipper dialect."
  - language: "BASIC"
    descr: "Is it serious that people use it yet?"
  - language: "C"
    descr: "When I need performance and direct communication with machine."
  - language: "C++"
    descr: "The most satanic language created by humans."
    language: "C#"
    descr: "It's what Java should be if Oracle weren't a dumbass!"
  - language: "Clipper"
    descr: "You'll never find good content about it on Internet..."
  - language: "Clojure"
    descr: "A LISP dialect, but so pure and beautiful."
  - language: "Coffeescript"
    descr: "Not as good as Livescript, but I also like it."
  - language: "Common LISP"
    descr: "Old? Yes! Lovely? Also! I <span class='heart'>♥</span> parenthesis!"
  - language: "Elixir"
    descr: "However, I prefer Erlang..."
  - language: "Erlang"
    descr: "Built to build concurrent webservers."
  - language: "F#"
    descr: "The better language of CLR that I ever knew!"
  - language: "(X) Harbour"
    descr: "The Clipper evolution."
  - language: "Haskell"
    descr: "A pure functional programming language."
  - language: "Haxe"
    descr: "A slave language to get shit done."
  - language: "Ink"
    descr: "A language I designed that compiles to ZPL."
  - language: "Hy"
    descr: "A LISP dialect that compiles to Python's AST."
  - language: "Java"
    descr: "No, I'm not proud of this."
  - language: "Javascript"
    descr: "Aka the Internet ASM."
  - language: "Livescript"
    descr: "An hybrid functional language that compiles to Javascript."
  - language: "Lua"
    descr: "Because I love prototypes and meta-tables."
  - language: "Matlab"
    descr: "A language created for scientific purposes."
  - language: "Nimrod"
    descr: "Efficient, expressive, and elegant, as they say."
  - language: "Paren"
    descr: "(Did (you (call (for (parenthesis ?)))))"
  - language: "Pascal"
    descr: "FPC best compiler implementation ever."
  - language: "PHP"
    descr: "Bitch, please! Do I need to say something?"
  - language: "Pogoscript"
    descr: "When I need to write a compile-to-js DSL."
  - language: "Purescript"
    descr: "Such purism, wow language!"
  - language: "Python"
    descr: "Not as pure as Ruby, but I love it."
  - language: "Ruby"
    descr: "Ah, such language, wow delicious!"
  - language: "Rust"
    descr: "When I getting so much segfaults in C, write it in Rust."
  - language: "Scala"
    descr: "An hybrid functional OO programming language."
  - language: "Shellscript"
    descr: "Everybody knows Shellscript. -.-'"
  - language: "Swift"
    descr: "Apple should allow me to write an open version..."
  - language: "Typescript"
    descr: "Because Microsoft sucks, but Microsoft Research is love!"
  - language: "Visual Basic"
    descr: "Argh!"
  - language: "Whip"
    descr: "Join LISP with Haskell, get Whip."
  - language: "ZPL"
    descr: "A language that runs on Zebra Printers (WTF!?)"

languages:
  - language: "Portuguese"
    descr: "Because it's my mother language, d'oh!"
  - language: "English"
    descr: "Who in the world doesn't know it?"
  - language: "Spanish"
    descr: "It has been useful sometimes."
  - language: "French"
    descr: "One of the best languages I ever learnt!"
  - language: "Mandarin"
    descr: "Yeah, it makes sense, taking account it's known by 1/6 of the world."
  - language: "Turkish"
    descr: "Why? Because turkish grammar is love!"
  - language: "Esperanto"
    descr: "Cause I'm too dumb to learn latin."

translation:
  - name: "phpMyAdmin"
    descr: "A web database manager system for MySQL."
    site: "http://www.phpmyadmin.net/"
  - name: "Geany"
    descr: "A soft and lightweight IDE."
    site: "http://www.geany.org"
  - name: "Mozilla Foundation"
    descr: "Translating technical articles about JS."
    site: "https://mozilla.org"
  - name: "Google"
    descr: "Helping improving Google Translator."
    site: "https://translate.google.com/"
  - name: "WikiMedia"
    descr: "Translator of the system behind Wikipedia."
    site: "https://wikimedia.org"
  - name: "WPS Office"
    descr: "A free alternative to Microsoft Office."
    site: "http://www.wsp.com"

contribution:
  - name: "Livescript"
    descr: "An hybrid language that compiles to Javascript."
    site: "http://livescript.net/"
  - name: "Typescript"
    descr: "A static typed language that compiles to Javascript."
    site: "www.typescriptlang.org/"
  - name: "HS Language PHP"
    descr: "Implementation of a PHP interpreter in Haskell."
    site: "https://github.com/jhartikainen/hs-language-php"

projects:
  - name: "Rawr"
    descr: "Implementation of static typing, functional programming and pure OO in PHP."
    site: "https://haskellcamargo.github.io/"
  - name: "Iguana OS"
    descr: "A web based operating system."
    site: "#"
  - name: "Prelude AdvPL"
    descr: "A port of Haskell's Prelude for AdvPL."
    site: "https://prelude.readthedocs.org/"
  - name: "RedeAssevim"
    descr: "A C# based network manager for my university."
    site: "https://github.com/haskellcamargo/redeassevim"
  - name: "Iguana Studio"
    descr: "A webkit IDE for building Iguana Apps."
    site: "https://github.com/haskellcamargo/iguanastudio"
  - name: "TSWM"
    descr: "A Typescript based windows manager for web."
    site: "https://github.com/haskellcamargo/TSWM"
  - name: "Prelude Erl"
    descr: "A port of Haskell's Prelude for Erlang."
    site: "https://github.com/haskellcamargo/Prelude-Erl"
  - name: "ThRust"
    descr: "Monadic implementation for Rust."
    site: "https://github.com/haskellcamargo/ThRust"
  - name: "Ink"
    descr: "Ink programming language."
    site: "https://github.com/haskellcamargo/ExtendedZPL"
  - name: "Rawr Lang"
    descr: "Rawr programming language."
    site: "https://github.com/haskellcamargo/rawr-lang"
  - name: "Shower"
    descr: "A better package manager for PHP, a port of NPM."
    https://github.com/haskellcamargo/shower
  - name: "PanDB"
    descr: "A small database system written in C and Rust."
    site: "https://github.com/haskellcamargo/pandb"