name: Capivaras
pygments: true

# navigation:
#   - text: Home
#     url: /index.html
#     group: home
#   - text: Docs
#     url: http://rawr.readthedocs.org
#     group: docs
#   - text: Getting Started
#     url: /getting-started/404.html
#     group: community

favorite:
  - language: Haskell
    descr: A pure functional programming language.
  - language: Livescript
    descr: An hybrid functional language that compiles to Javascript.
  - language: F#
    descr: The better language of CLR that I ever knew!
  - language: Erlang
    descr: Built to build concurrent webservers.

proglang:
  - language: "Ada"
    descr: "We have the real time and the Ada time."
  - language: "AdvPL"
    descr: "A proprietary language built by Totvs, a Clipper dialect."
  - language: "BASIC"
    descr: "Is it serious that people use it yet?"
  - language: "C"
    descr: "When I need performance and direct communication with machine."
  - language: "C++"
    descr: "The most satanic language created by humans."
    language: "C#"
    descr: "It's what Java should be if Oracle weren't a dumbass!"
  - language: "Clipper"
    descr: "You'll never find good content about it on Internet..."
  - language: "Clojure"
    descr: "A LISP dialect, but so pure and beautiful."
  - language: "Coffeescript"
    descr: "Not as good as Livescript, but I also like it."
  - language: "Common LISP"
    descr: "Old? Yes! Lovely? Also! I <span class='heart'>♥</span> parenthesis!"
  - language: "Elixir"
    descr: "However, I prefer Erlang..."
  - language: "Erlang"
    descr: "Built to build concurrent webservers."
  - language: "F#"
    descr: "The better language of CLR that I ever knew!"
  - language: "(X) Harbour"
    descr: "The Clipper evolution."
  - language: "Haskell"
    descr: "A pure functional programming language."
  - language: "Haxe"
    descr: "A slave language to get shit done."
  - language: "Ink"
    descr: "A language I designed that compiles to ZPL."
  - language: "Hy"
    descr: "A LISP dialect that compiles to Python's AST."
  - language: "Java"
    descr: "No, I'm not proud of this."
  - language: "Javascript"
    descr: "Aka the Internet ASM."
  - language: "Livescript"
    descr: "An hybrid functional language that compiles to Javascript."
  - language: "Lua"
    descr: "Because I love prototypes and meta-tables."
  - language: "Matlab"
    descr: "A language created for scientific purposes."
  - language: "Nimrod"
    descr: "Efficient, expressive, and elegant, as they say."
  - language: "Paren"
    descr: "(Did (you (call (for (parenthesis ?)))))"
  - language: "Pascal"
    descr: "FPC best compiler implementation ever."
  - language: "PHP"
    descr: "Bitch, please! Do I need to say something?"
  - language: "Pogoscript"
    descr: "When I need to write a compile-to-js DSL."
  - language: "Purescript"
    descr: "Such purism, wow language!"
  - language: "Python"
    descr: "Not as pure as Ruby, but I love it."
  - language: "Ruby"
    descr: "Ah, such language, wow delicious!"
  - language: "Rust"
    descr: "When I getting so much segfaults in C, write it in Rust."
  - language: "Scala"
    descr: "An hybrid functional OO programming language."
  - language: "Shellscript"
    descr: "Everybody knows Shellscript. -.-'"
  - language: "Swift"
    descr: "Apple should allow me to write an open version..."
  - language: "Typescript"
    descr: "Because Microsoft sucks, but Microsoft Research is love!"
  - language: "Visual Basic"
    descr: "Argh!"
  - language: "Whip"
    descr: "Join LISP with Haskell, get Whip."
  - language: "ZPL"
    descr: "A language that runs on Zebra Printers (WTF!?)"

languages:
  - Portuguese
  - English
  - Spanish
  - French
  - Turkish
  - Mandarin
  - Esperanto